services:
  - type: web
    name: preload-md
    runtime: python
    rootDir: backend
    env: python
    buildCommand: pip install --upgrade pip setuptools && pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.6"
      - key: APP_ENV
        value: production
      - key: CORS_ORIGINS
        value: '["https://onboarding-mdigital-peach.vercel.app"]'
